"use client";

import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 11, fontFamily: "Helvetica" },
  header: { flexDirection: "row", justifyContent: "space-between", marginBottom: 24 },
  brand: { fontSize: 20, fontWeight: 700, color: "#1F4E79" },
  label: { color: "#888", fontSize: 9, textTransform: "uppercase" },
  value: { fontSize: 11, marginBottom: 8 },
  table: { marginTop: 20, borderTop: "1 solid #ddd" },
  row: { flexDirection: "row", borderBottom: "1 solid #eee", paddingVertical: 8 },
  headerRow: { flexDirection: "row", backgroundColor: "#1F4E79", padding: 8 },
  headerCell: { color: "#fff", fontSize: 9, textTransform: "uppercase", flex: 1 },
  headerCellWide: { color: "#fff", fontSize: 9, textTransform: "uppercase", flex: 2.2 },
  cell: { flex: 1, fontSize: 10 },
  cellWide: { flex: 2.2, fontSize: 10 },
  totalRow: { flexDirection: "row", justifyContent: "flex-end", marginTop: 16 },
  totalLabel: { fontSize: 12, fontWeight: 700, marginRight: 12 },
  totalValue: { fontSize: 12, fontWeight: 700, color: "#1F4E79" },
  footer: { marginTop: 40, fontSize: 9, color: "#999", textAlign: "center" },
});

export type InvoiceLineItem = {
  productName: string;
  quantity: number;
  unitPrice: number;
  subtotal: number;
};

export type InvoiceData = {
  invoiceNumber: string;
  date: string;
  customerName: string;
  items: InvoiceLineItem[];
  totalAmount: number;
};

export default function InvoiceDocument({ data }: { data: InvoiceData }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <View>
            <Text style={styles.brand}>Stockwise</Text>
            <Text style={{ fontSize: 9, color: "#888" }}>Business Management Receipt</Text>
          </View>
          <View>
            <Text style={styles.label}>Invoice No.</Text>
            <Text style={styles.value}>{data.invoiceNumber}</Text>
            <Text style={styles.label}>Date</Text>
            <Text style={styles.value}>{data.date}</Text>
          </View>
        </View>

        <Text style={styles.label}>Billed To</Text>
        <Text style={{ ...styles.value, fontSize: 13, fontWeight: 700 }}>{data.customerName}</Text>

        <View style={styles.table}>
          <View style={styles.headerRow}>
            <Text style={styles.headerCellWide}>Product</Text>
            <Text style={styles.headerCell}>Qty</Text>
            <Text style={styles.headerCell}>Unit Price</Text>
            <Text style={styles.headerCell}>Subtotal</Text>
          </View>
          {data.items.map((item, i) => (
            <View style={styles.row} key={i} wrap={false}>
              <Text style={styles.cellWide}>{item.productName}</Text>
              <Text style={styles.cell}>{item.quantity}</Text>
              <Text style={styles.cell}>{"\u20a6" + item.unitPrice.toLocaleString()}</Text>
              <Text style={styles.cell}>{"\u20a6" + item.subtotal.toLocaleString()}</Text>
            </View>
          ))}
        </View>

        <View style={styles.totalRow}>
          <Text style={styles.totalLabel}>Total</Text>
          <Text style={styles.totalValue}>{"\u20a6" + data.totalAmount.toLocaleString()}</Text>
        </View>

        <Text style={styles.footer}>Thank you for your business \- generated by Stockwise</Text>
      </Page>
    </Document>
  );
}
